name: Release
on:
  push:
    tags: ['v*']
jobs:
  build:
    uses: oprobiu/AFAS/.github/workflows/build-release.yml@v0.3.0
    with:
      deck-configs: 'data/ro/deck.json,data/en/deck.json'
      tools-version: v0.3.0
    permissions:
      contents: write
